# TAREA 2-A: Estructura de una matriz

___Nivel 1___

___EJERCICIO 1___

In [18]:
#importación de librerias

import numpy as np
from numpy import random

# creación de array de una dimensión

arr = np.random.randint(100, size=(8))

print(arr)
print('el tipo de dato de la array es:', arr.dtype)
print('la dimensión de array es:', arr.ndim)


[18 29 13 28 61 99  1 83]
el tipo de dato de la array es: int32
la dimensión de array es: 1


___EJERCICIO 2___

In [37]:
#calcular la media y restar la mediana de cada valor.

print('La media es:', arr.mean())

print('La mediana es:', np.median(arr))

print('la resta de la mediana y la media sería', arr.mean() - np.median(arr))


La media es: 41.5
La mediana es: 28.5
la resta de la mediana y la media sería 13.0


___EJERCICIO 3___

In [51]:
#creación de matriz 2D
x = random.randint(100, size=(5, 5))

print(x)

print('Dimensión de la matriz:',x.ndim)
print('El valor máximo de la matriz 2D es:', x.max())
print('Los valores máximos de cada eje de la matriz 2D es:', x.max(axis=0))


[[14 39 88  1  4]
 [29  2 97 88  8]
 [56 73 84 40  8]
 [24 68 66  4  5]
 [19 99 82 73 42]]
Dimensión de la matriz: 2
El valor máximo de la matriz 2D es: 99
Los valores máximos de cada eje de la matriz 2D es: [56 99 97 88 42]
